Update
mali-28/burger-app pull request #2
Opened 2021-09-14 14:17 UTC by mali-28

add loading effect on signup and login
only active/login user orders will be show
split  components

2021-10-24 17:14 UTC, mtahir08 requested changes

2021-10-24 17:14 UTC, mtahir08 commented on src/Reducer/reducer.js
> +    }
this is same as variable `quantity` you can return quantity instead of this complete object again

2021-10-24 17:14 UTC, mtahir08 commented on src/components/HomeContent.js
> +              {lettuce?.map((val, id) => { return <div key={id} className="w-40 h-05 bg-lettuce m-02"></div> })}
please use `_val` instead of `val` if the variable in loop will not use

2021-10-24 17:14 UTC, mtahir08 commented on src/components/HomeContent.js
> +                  <Count  title={val.title} price={val.price} />
if product only have title and price then pass {...val} only

2021-10-24 17:14 UTC, mtahir08 commented on src/components/HomeContent.js
> +                background: !productPrice ? "#83591a" : "#D8AC68",
reverse it. otherwise ! add the complexity in logic
`productPrice ? "#D8AC68" : "#83591a" ,`

2021-10-24 17:14 UTC, mtahir08 commented on src/components/HomeContent.js
> +      <DialogBox total={productPrice} onClose={handleDialog} open={open} counter={props.counter}   remove={() => { props.remove() }} />
if parameter not needed then you can just pass function name
`remove={props.remove}` it will automatically call it

2021-10-24 17:14 UTC, mtahir08 commented on src/components/InputField.jsx
> +      <input type={type || "text"} onChange={onChange} name={name} className="input f-family-monospace " placeholder={placeholder} value={props.value} disabled={props.disabled || false}/>
no need to pass {props.disabled || false} just pass {props.disabled}

2021-10-24 17:14 UTC, mtahir08 commented on src/components/TopBar.js
> +            <NavLink onClick={()=>{setLogin(localStorage.removeItem("Islogin"), setUser(localStorage.removeItem("__USER__")))}}  className="p-022-3-016-3 white t-decoration-none  f-family-monospace"
try not to use logics in return. instead make a function and call it then add all logics in that function

2021-10-24 17:14 UTC, mtahir08 commented on src/routes/UserLogin.jsx
> +                            setLogin(setLocalStorage("Islogin",response.token))
why you did same thing 3 times?

2021-10-25 06:42 UTC, mali-28 commented on src/Reducer/reducer.js
> +    }
reference problem 
 const rmvState = JSON.parse(JSON.stringify(quantity))
      return rmvState;

2021-10-25 06:43 UTC, mali-28 commented on src/routes/UserLogin.jsx
> +                            setLogin(setLocalStorage("Islogin",response.token))
by mistake

2021-10-26 19:12 UTC, mtahir08 approved these changes

2021-10-26 19:12 UTC, merged